<a href="https://colab.research.google.com/github/AyeshathHafeeza/DataScience/blob/main/Numpy_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Basic Functions**

---



In [ ]:
import numpy as np

In [ ]:
# Creates a NumPy array from a list or tuple.
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
# Creates a range of values with a step.
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# Generates evenly spaced values between a start and end.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Creates an array of zeros.
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Creates an array of ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Generates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Changes array shape without changing the data.
arr=np.array([4,5,3,2,6,7])
arr.reshape(2, 3)

array([[4, 5, 3],
       [2, 6, 7]])

In [ ]:
# Adds all elements.
np.sum(arr)

np.int64(27)

In [ ]:
# Calculates average value.
np.mean(arr)

np.float64(4.5)

In [ ]:
# Computes standard deviation.
np.std(arr)

np.float64(1.707825127659933)

In [ ]:
# Finds smallest
np.min(arr)

np.int64(2)

In [ ]:
# Finds largest
np.max(arr)

np.int64(7)

In [ ]:
# Generates random numbers between 0 and 1.
np.random.rand(3)

array([0.77743246, 0.48944512, 0.93960212])

In [ ]:
# Random integers in a specified range.
np.random.randint(1, 100)

20

In [ ]:
# Combines arrays.
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Returns unique elements.
np.unique(arr)

array([2, 3, 4, 5, 6, 7])

In [ ]:
# Sorts an array.
np.sort(arr)

array([2, 3, 4, 5, 6, 7])

In [ ]:
# Access specific rows, columns and slices.

arr[:]

array([4, 5, 3, 2, 6, 7])

In [ ]:
# Returns positions where condition is true.
np.where(arr > 6)

(array([5]),)

In [ ]:
# Matrix multiplication / dot product.
np.dot(a, b)

np.int64(70)

In [ ]:
print(arr)

[4 5 3 2 6 7]


In [ ]:
# Swaps rows and columns
arr.T

array([4, 5, 3, 2, 6, 7])