<a href="https://colab.research.google.com/github/AyeshathHafeeza/DataScience/blob/main/NumPy_Basic_Assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assessment 1**

In [ ]:
import numpy as np
#  Create a NumPy array from this list:
# [4, 8, 12, 16, 20]
arr=np.array([4, 8, 12, 16, 20])
print(arr)


[ 4  8 12 16 20]


In [ ]:
#  Generate an array of numbers from 1 to 30 with a step of 3
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
# Create an array of 5 evenly spaced numbers between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3×3 matrix of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Create a 2×4 matrix of ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Reshape this array into 3 rows and 2 columns:
s=np.array([1,2,3,4,5,6])
arr.reshape(3,2)

array([[ 4,  8],
       [12, 16],
       [20,  1]])

In [ ]:
# Find the:
# sum
np.sum(arr)

np.float64(10.166666666666666)

In [ ]:
# mean
np.mean(arr)

np.float64(10.166666666666666)

In [ ]:
# max
np.max(arr)

np.int64(20)

In [ ]:
#min
np.min(arr)

np.int64(1)

In [ ]:
# sort the array
a=np.array([9,2,7,1,6])
np.sort(a)

array([1, 2, 6, 7, 9])

# **Assessment 2**

In [ ]:
#  Generate an array of 5 random integers between 10 and 50
import random
np.random.randint(10,50,5)

array([20, 45, 32, 13, 32])

In [ ]:
# Generate a 2×3 matrix of random values between 0 and 1
np.random.rand(2,3)

array([[0.13498453, 0.32748718, 0.46475566],
       [0.70974007, 0.5749516 , 0.8092288 ]])

In [ ]:
# Combine these two arrays into one

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# From this array:
# arr = np.array([3, 7, 2, 7, 9, 2, 3])
# Find the unique values.
arr = np.array([3, 7, 2, 7, 9, 2, 3])
np.unique(arr)

array([2, 3, 7, 9])

In [ ]:
#  Using this matrix:
# A = np.array([[1, 2],[3, 4]])
# Calculate its transpose.
A = np.array([[1, 2],[3, 4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [ ]:
# Perform matrix multiplication:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
# Find the indices where elements of this array are greater than 50:
arr = np.array([12, 67, 45, 89, 23])
np.where(arr>50)

(array([1, 3]),)