<a href="https://colab.research.google.com/github/AyeshathHafeeza/DataScience/blob/main/Weather_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Weather Analysis**

In [51]:
import pandas as pd
import numpy as np

In [52]:
df=pd.read_csv("/content/weather_data- Numpy 1st assesment.csv")
print(df.to_string())

   Day  Temperature  Humidity
0    1           29        68
1    2           31        72
2    3           33        70
3    4           30        75
4    5           28        65
5    6           27        63
6    7           32        71


In [53]:
#  Create a 2D array combining Temperature and Humidity
x=df['Humidity']
y=df['Temperature']
arr=np.array([x,y])
print(arr)

[[68 72 70 75 65 63 71]
 [29 31 33 30 28 27 32]]


In [54]:
# Generate an array of missing days from 1 to 10
full_days=np.arange(1,11)
present_days=np.arange(1,8)
missing_days = np.setdiff1d(full_days, present_days)
print(missing_days)

[ 8  9 10]


In [55]:
# Create 5 evenly spaced test values between min & max temperature
minimum=df['Temperature'].min()
maximum=df['Temperature'].max()
np.linspace(minimum,maximum,5)

array([27. , 28.5, 30. , 31.5, 33. ])

In [56]:
#  Create a 7×1 array of zeros.
np.zeros((7,1))


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [57]:
#  Create a 7×1 array of ones.
np.ones((7,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [58]:
df['Temperature']

0    29
1    31
2    33
3    30
4    28
5    27
6    32
Name: Temperature, dtype: int64

In [59]:
# Reshape temperature into a 7×1 matrix
np.reshape(df['Temperature'],(7,1))

array([[29],
       [31],
       [33],
       [30],
       [28],
       [27],
       [32]])

In [60]:
# Calculate the following for temperature:
# sum
np.sum(df['Temperature'])

np.int64(210)

In [61]:
# mean
np.mean(df['Temperature'])

np.float64(30.0)

In [62]:
# Max
np.max(df['Temperature'])

33

In [63]:
# min
np.min(df['Temperature'])

27

In [64]:
# Sort humidity values
np.sort(df['Humidity'])

array([63, 65, 68, 70, 71, 72, 75])

In [65]:
# Generate 7 random humidity errors between -3 and +3
np.random.randint(-3,4,7)

array([-2,  0,  3,  1, -2,  0,  2])

In [66]:
# Generate 7 random temperature fluctuations (0-1 range)
np.random.rand(7)

array([0.43014859, 0.82498433, 0.20844835, 0.86061755, 0.13785645,
       0.05537855, 0.6101825 ])

In [67]:
df['Humidity']

0    68
1    72
2    70
3    75
4    65
5    63
6    71
Name: Humidity, dtype: int64

In [68]:
# Find unique humidity values.
np.unique(df['Humidity'])

array([63, 65, 68, 70, 71, 72, 75])

In [72]:
# Combine temperature and humidity into a single long array.
combined=np.concatenate((df['Temperature'],df['Humidity']))
print(combined)

[29 31 33 30 28 27 32 68 72 70 75 65 63 71]


In [85]:
# Create a 7×2 weather matrix and find humidity column.
weather=np.array(df[['Temperature','Humidity']])
print(weather)

[[29 68]
 [31 72]
 [33 70]
 [30 75]
 [28 65]
 [27 63]
 [32 71]]


In [88]:
humidity_column=weather[:,1]
print(humidity_column)

[68 72 70 75 65 63 71]


In [89]:
# Find temperatures greater than 30°C
np.where(df['Temperature']>30)

(array([1, 2, 6]),)

In [90]:
# Transpose the weather matrix
weather.T

array([[29, 31, 33, 30, 28, 27, 32],
       [68, 72, 70, 75, 65, 63, 71]])

In [93]:
# Perform dot product: Temperature × Humidity (element-wise sum)
np.dot(df['Temperature'],df['Humidity'])

np.int64(14557)

In [94]:
# Create an identity matrix of size 3.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
#  Create a 3×3 grid of ones for weather testing.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
# Slice the first 4 days humidity.
hum=weather[:4,1]
print(hum)

[68 72 70 75]


In [101]:
# Slice the last 3 temperature values.
last_temp=weather[-3:,0]
print(last_temp)

[28 27 32]


In [102]:
#  Compare humidity > 70 and display all such days
np.where(df['Humidity']>70)

(array([1, 3, 6]),)